// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFcNWoUUMxmbmwelad6NdjG7VLPFNP2dg',
    appId: '1:305892888335:web:30e75326c06012438cb87a',
    messagingSenderId: '305892888335',
    projectId: 'ticktick-4456a',
    authDomain: 'ticktick-4456a.firebaseapp.com',
    storageBucket: 'ticktick-4456a.firebasestorage.app',
    measurementId: 'G-REPW64NMX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAphy7p44ZU4BKjZxBblZnq2qJKPPERuLs',
    appId: '1:305892888335:android:8e47f2d6d2a9d10b8cb87a',
    messagingSenderId: '305892888335',
    projectId: 'ticktick-4456a',
    storageBucket: 'ticktick-4456a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-qgGYT4hWGgfWfuN2o3J0-IRiaLqvGR8',
    appId: '1:305892888335:ios:4a786c815824d9b78cb87a',
    messagingSenderId: '305892888335',
    projectId: 'ticktick-4456a',
    storageBucket: 'ticktick-4456a.firebasestorage.app',
    iosBundleId: 'com.example.ticktick',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-qgGYT4hWGgfWfuN2o3J0-IRiaLqvGR8',
    appId: '1:305892888335:ios:4a786c815824d9b78cb87a',
    messagingSenderId: '305892888335',
    projectId: 'ticktick-4456a',
    storageBucket: 'ticktick-4456a.firebasestorage.app',
    iosBundleId: 'com.example.ticktick',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFcNWoUUMxmbmwelad6NdjG7VLPFNP2dg',
    appId: '1:305892888335:web:1aa98951c27398608cb87a',
    messagingSenderId: '305892888335',
    projectId: 'ticktick-4456a',
    authDomain: 'ticktick-4456a.firebaseapp.com',
    storageBucket: 'ticktick-4456a.firebasestorage.app',
    measurementId: 'G-9EMR1DDW2B',
  );
}
